package com.danasys.dto;

public enum TransactionTypeEnum {

	/*
	 * PAYMENT, REFUND, REFUND_CREDIT, REFERRAL_CREDIT, REFERRAL_REVOKE,
	 * REFUND_CREDIT_UNCLEARED , REFUND_CREDIT_UNCLER_TO_CLEARED,
	 * PAYMENT_TRANSFER_TO_ACCOUNT, UNCLEARED_TO_CLEARED_AMOUNT,
	 * UNCLEARED_TO_CLEARED_POINT, REDEEMED_RFFERAL_POINT,
	 * TRANSFER_REFERAL_TO_ACCOUNT_REQ, TRANSFERED_REFERAL_TO_ACCOUNT,
	 */
	 
	 
	 //SHOPPING USER STATUS
	 USER_PAYMENT_TXN,
	 USER_REFUND_UNCLEARED_CREDIT,
	 USER_REFUND_CLEARED_CREDIT,
	 USER_REFUND_CLEARED_TXN,
	 USER_PAYMNT_TO_BANK_DEBIT,
	 USER_PAYMNT_TO_BANK_REQ,
	 
	 
	 //PLATFORM STATUS
	 PLATFORM_PAYMENT_CREDIT,
	 PLATFORM_USER_PAYMENT_DEBIT,
	 PLAFORM_PAYMENT_TO_ACC_TXN,
	 
	 
	 // BU USER
	 BU_UNCLEARED_PAYMENT_CREDIT,
	 BU_CLEARED_PAYMENT_TXN,
	 BU_PAYMENT_TO_BANK_REQ,
	 BU_PAYMENT_TO_BANK_DEBIT,
	 BU_UNCLEARED_REFUND_DEBIT,
	 
	 //REFERAL USER STATUS
	 REFFERAL_UNCLEARED_POINT_CREDIT,
	 REFERRAL_UNCLEARED_POINT_REVOKE_DEBIT,
	 REFERRAL_UNCLEARED_TO_CLEARED_TXN,
	 REFFERAL_REDEEMED_CLEARED_POINT_TXN
	 
}
