package com.danasys.user.enums;

public enum TransferRequestTypeEnum {

	WALLET_TO_BANK_REQ, UNCLEARED_TO_WALLET_REQ, REFFERAL_TO_WALLET_REQ, UNCLEAR_REFFERAL_TO_REFERAL_REQ,
	
	WALLET_TO_BANK_DONE, UNCLEARED_TO_WALLET_DONE, REFFERAL_TO_WALLET_DONE, UNCLEAR_REFFERAL_TO_REFERAL_DONE;
}
